# Site settings

title: "Bulma: a modern CSS framework based on Flexbox"
description: > # this means to ignore newlines until "baseurl:"
  Bulma is a CSS framework based on Flexbox and built with Sass
baseurl: ""
cssurl: "/styles/bulma-website.css"
url: "http://bulma.io"
github: "https://github.com/jgthms/bulma"
download: "https://github.com/jgthms/bulma/archive/0.1.2.zip"
version: 0.1.2
permalink: pretty
documentation: "/documentation/overview/start/"

# Build settings

markdown: kramdown
